/// Flutter icons BottomTabsIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomTabsIcons
///      fonts:
///       - asset: fonts/BottomTabsIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class BottomTabsIcons {
  BottomTabsIcons._();

  static const _kFontFam = 'BottomTabsIcons';
  static const String? _kFontPkg = null;

  static const IconData add_location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_can = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
